// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53M7FfRxPYNlQcBqxDj4GazJYxjgFnLY',
    appId: '1:81092546078:web:c4ba400e0f90e180ec680f',
    messagingSenderId: '81092546078',
    projectId: 'guide-touristique-app',
    authDomain: 'guide-touristique-app.firebaseapp.com',
    storageBucket: 'guide-touristique-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdnl_oSV4liQiVxJ7hRRHYeR802Kcf-rg',
    appId: '1:81092546078:android:82c91df0a00eecefec680f',
    messagingSenderId: '81092546078',
    projectId: 'guide-touristique-app',
    storageBucket: 'guide-touristique-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUh73mVLLmm4h4B7rF1fCaWcJm1ENEKpc',
    appId: '1:81092546078:ios:9d87f30ec3f2d78aec680f',
    messagingSenderId: '81092546078',
    projectId: 'guide-touristique-app',
    storageBucket: 'guide-touristique-app.firebasestorage.app',
    iosBundleId: 'com.example.guideTouristique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUh73mVLLmm4h4B7rF1fCaWcJm1ENEKpc',
    appId: '1:81092546078:ios:9d87f30ec3f2d78aec680f',
    messagingSenderId: '81092546078',
    projectId: 'guide-touristique-app',
    storageBucket: 'guide-touristique-app.firebasestorage.app',
    iosBundleId: 'com.example.guideTouristique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD53M7FfRxPYNlQcBqxDj4GazJYxjgFnLY',
    appId: '1:81092546078:web:0b75b7bdce5e4859ec680f',
    messagingSenderId: '81092546078',
    projectId: 'guide-touristique-app',
    authDomain: 'guide-touristique-app.firebaseapp.com',
    storageBucket: 'guide-touristique-app.firebasestorage.app',
  );

}